### PR TITLE
[D] Add basic documentation

### LINKED ISSUE #30: TsDocs for API documentation.
Use https://github.com/Microsoft/tsdoc for documentation of API and host it in gh-pages.

Expected outcomes:
* [ ] High level concepts
* [ ] Documentation of the event store public API, with explanations of any internal behaviour that should be considered during usage. Things like events not being saved prior to a listener being called, etc.### 
* [ ] Automatic doc generation based on the latest build from the master branch on CI.

### PR DESCRIPTION
**Pull request by jamwaffles**
This PR

* Migrates from NPM to Yarn (because why not)
* Adds [Typedoc](http://typedoc.org/)
* Adds `yarn doc` command, generating output into `doc/`
* Adds minimal documentation for the most commonly used parts of the event store
* Removes as many `string` types as possible and adds type aliases for them
* Runs `prettier` on the `src/` directory

Closes #30 

TODO (for another PR)

* [ ] Create release process
* [ ] Generate documentation in CI and publish to Github Pages as part of release process

### CODE REVIEW

**Comment by Istar-Eldritch** [comment]
Should we add github pages with the docs?

**Comment by jamwaffles** [comment]
> Should we add github pages with the docs?

Absolutely! If you could give me admin access to this repo I can set that up.

**Comment by Istar-Eldritch** [comment]
granted.

**Comment by Istar-Eldritch** [comment]
@jamwaffles I think we should do the GitHub pages as a different branch instead of using a `docs` folder. Do you agree? We can setup circleci to publish them or we can do it manually for now. What do you think?

**Comment by jamwaffles** [comment]
Yeah I gave up on all that last night. I want to push docs to gh-pages as part of the release process, wherever and however that happens. I'll do some prototyping.

**Comment by Istar-Eldritch** [comment]
If you want we can merge this one and we do the doc automation in a different PR

**Comment by jamwaffles** [comment]
Let's go with that. We can do a one-off manual generation for gh-pages once this is merged so people have _something_ to work with.

**Comment by Istar-Eldritch** [comment]
Approved :+1:

**Pull request merged**
