### PR TITLE
[F] Unifier utility

### PR DESCRIPTION
**Pull request by jamwaffles**
dsfdgfsdfgafdbtyjaerotpjgertnu45n69078qhearfgq8907g4rlosadfgbhadjgmnyn q345o7utsrthnw49856yn2w[p40nhg5o2p045yn[2p408ny6h24p-0w65yjh2409yn4wqp57gh248w765tgq34-pt9hb4w2-5p[hw24['y58h-q4[p9gbuq4-097gbw4p958gyh['dsfdgfsdfgafdbtyjaerotpjgertnu45n69078qhearfgq8907g4rlosadfgbhadjgmnyn q345o7utsrthnw49856yn2w[p40nhg5o2p045yn[2p408ny6h24p-0w65yjh2409yn4wqp57gh248w765tgq34-pt9hb4w2-5p[hw24['y58h-q4[p9gbuq4-097gbw4p958gyh['dsfdgfsdfgafdbtyjaerotpjgertnu45n69078qhearfgq8907g4rlosadfgbhadjgmnyn q345o7utsrthnw49856yn2w[p40nhg5o2p045yn[2p408ny6h24p-0w65yjh2409yn4wqp57gh248w765tgq34-pt9hb4w2-5p[hw24['y58h-q4[p9gbuq4-097gbw4p958gyh['dsfdgfsdfgafdbtyjaerotpjgertnu45n69078qhearfgq8907g4rlosadfgbhadjgmnyn q345o7utsrthnw49856yn2w[p40nhg5o2p045yn[2p408ny6h24p-0w65yjh2409yn4wqp57gh248w765tgq34-pt9hb4w2-5p[hw24['y58h-q4[p9gbuq4-097gbw4p958gyh['dsfdgfsdfgafdbtyjaerotpjgertnu45n69078qhearfgq8907g4rlosadfgbhadjgmnyn q345o7utsrthnw49856yn2w[p40nhg5o2p045yn[2p408ny6h24p-0w65yjh2409yn4wqp57gh248w765tgq34-pt9hb4w2-5p[hw24['y58h-q4[p9gbuq4-097gbw4p958gyh['dsfdgfsdfgafdbtyjaerotpjgertnu45n69078qhearfgq8907g4rlosadfgbhadjgmnyn q345o7utsrthnw49856yn2w[p40nhg5o2p045yn[2p408ny6h24p-0w65yjh2409yn4wqp57gh248w765tgq34-pt9hb4w2-5p[hw24['y58h-q4[p9gbuq4-097gbw4p958gyh['dsfdgfsdfgafdbtyjaerotpjgertnu45n69078qhearfgq8907g4rlosadfgbhadjgmnyn q345o7utsrthnw49856yn2w[p40nhg5o2p045yn[2p408ny6h24p-0w65yjh2409yn4wqp57gh248w765tgq34-pt9hb4w2-5p[hw24['y58h-q4[p9gbuq4-097gbw4p958gyh['dsfdgfsdfgafdbtyjaerotpjgertnu45n69078qhearfgq8907g4rlosadfgbhadjgmnyn q345o7utsrthnw49856yn2w[p40nhg5o2p045yn[2p408ny6h24p-0w65yjh2409yn4wqp57gh248w765tgq34-pt9hb4w2-5p[hw24['y58h-q4[p9gbuq4-097gbw4p958gyh['dsfdgfsdfgafdbtyjaerotpjgertnu45n69078qhearfgq8907g4rlosadfgbhadjgmnyn q345o7utsrthnw49856yn2w[p40nhg5o2p045yn[2p408ny6h24p-0w65yjh2409yn4wqp57gh248w765tgq34-pt9hb4w2-5p[hw24['y58h-q4[p9gbuq4-097gbw4p958gyh['dsfdgfsdfgafdbtyjaerotpjgertnu45n69078qhearfgq8907g4rlosadfgbhadjgmnyn q345o7utsrthnw49856yn2w[p40nhg5o2p045yn[2p408ny6h24p-0w65yjh2409yn4wqp57gh248w765tgq34-pt9hb4w2-5p[hw24['y58h-q4[p9gbuq4-097gbw4p958gyh['dsfdgfsdfgafdbtyjaerotpjgertnu45n69078qhearfgq8907g4rlosadfgbhadjgmnyn q345o7utsrthnw49856yn2w[p40nhg5o2p045yn[2p408ny6h24p-0w65yjh2409yn4wqp57gh248w765tgq34-pt9hb4w2-5p[hw24['y58h-q4[p9gbuq4-097gbw4p958gyh['dsfdgfsdfgafdbtyjaerotpjgertnu45n69078qhearfgq8907g4rlosadfgbhadjgmnyn q345o7utsrthnw49856yn2w[p40nhg5o2p045yn[2p408ny6h24p-0w65yjh2409yn4wqp57gh248w765tgq34-pt9hb4w2-5p[hw24['y58h-q4[p9gbuq4-097gbw4p958gyh['dsfdgfsdfgafdbtyjaerotpjgertnu45n69078qhearfgq8907g4rlosadfgbhadjgmnyn q345o7utsrthnw49856yn2w[p40nhg5o2p045yn[2p408ny6h24p-0w65yjh2409yn4wqp57gh248w765tgq34-pt9hb4w2-5p[hw24['y58h-q4[p9gbuq4-097gbw4p958gyh['dsfdgfsdfgafdbtyjaerotpjgertnu45n69078qhearfgq8907g4rlosadfgbhadjgmnyn q345o7utsrthnw49856yn2w[p40nhg5o2p045yn[2p408ny6h24p-0w65yjh2409yn4wqp57gh248w765tgq34-pt9hb4w2-5p[hw24['y58h-q4[p9gbuq4-097gbw4p958gyh['dsfdgfsdfgafdbtyjaerotpjgertnu45n69078qhearfgq8907g4rlosadfgbhadjgmnyn q345o7utsrthnw49856yn2w[p40nhg5o2p045yn[2p408ny6h24p-0w65yjh2409yn4wqp57gh248w765tgq34-pt9hb4w2-5p[hw24['y58h-q4[p9gbuq4-097gbw4p958gyh['dsfdgfsdfgafdbtyjaerotpjgertnu45n69078qhearfgq8907g4rlosadfgbhadjgmnyn q345o7utsrthnw49856yn2w[p40nhg5o2p045yn[2p408ny6h24p-0w65yjh2409yn4wqp57gh248w765tgq34-pt9hb4w2-5p[hw24['y58h-q4[p9gbuq4-097gbw4p958gyh['dsfdgfsdfgafdbtyjaerotpjgertnu45n69078qhearfgq8907g4rlosadfgbhadjgmnyn q345o7utsrthnw49856yn2w[p40nhg5o2p045yn[2p408ny6h24p-0w65yjh2409yn4wqp57gh248w765tgq34-pt9hb4w2-5p[hw24['y58h-q4[p9gbuq4-097gbw4p958gyh['dsfdgfsdfgafdbtyjaerotpjgertnu45n69078qhearfgq8907g4rlosadfgbhadjgmnyn q345o7utsrthnw49856yn2w[p40nhg5o2p045yn[2p408ny6h24p-0w65yjh2409yn4wqp57gh248w765tgq34-pt9hb4w2-5p[hw24['y58h-q4[p9gbuq4-097gbw4p958gyh['dsfdgfsdfgafdbtyjaerotpjgertnu45n69078qhearfgq8907g4rlosadfgbhadjgmnyn q345o7utsrthnw49856yn2w[p40nhg5o2p045yn[2p408ny6h24p-0w65yjh2409yn4wqp57gh248w765tgq34-pt9hb4w2-5p[hw24['y58h-q4[p9gbuq4-097gbw4p958gyh['dsfdgfsdfgafdbtyjaerotpjgertnu45n69078qhearfgq8907g4rlosadfgbhadjgmnyn q345o7utsrthnw49856yn2w[p40nhg5o2p045yn[2p408ny6h24p-0w65yjh2409yn4wqp57gh248w765tgq34-pt9hb4w2-5p[hw24['y58h-q4[p9gbuq4-097gbw4p958gyh['dsfdgfsdfgafdbtyjaerotpjgertnu45n69078qhearfgq8907g4rlosadfgbhadjgmnyn q345o7utsrthnw49856yn2w[p40nhg5o2p045yn[2p408ny6h24p-0w65yjh2409yn4wqp57gh248w765tgq34-pt9hb4w2-5p[hw24['y58h-q4[p9gbuq4-097gbw4p958gyh['dsfdgfsdfgafdbtyjaerotpjgertnu45n69078qhearfgq8907g4rlosadfgbhadjgmnyn q345o7utsrthnw49856yn2w[p40nhg5o2p045yn[2p408ny6h24p-0w65yjh2409yn4wqp57gh248w765tgq34-pt9hb4w2-5p[hw24['y58h-q4[p9gbuq4-097gbw4p958gyh['dsfdgfsdfgafdbtyjaerotpjgertnu45n69078qhearfgq8907g4rlosadfgbhadjgmnyn q345o7utsrthnw49856yn2w[p40nhg5o2p045yn[2p408ny6h24p-0w65yjh2409yn4wqp57gh248w765tgq34-pt9hb4w2-5p[hw24['y58h-q4[p9gbuq4-097gbw4p958gyh['dsfdgfsdfgafdbtyjaerotpjgertnu45n69078qhearfgq8907g4rlosadfgbhadjgmnyn q345o7utsrthnw49856yn2w[p40nhg5o2p045yn[2p408ny6h24p-0w65yjh2409yn4wqp57gh248w765tgq34-pt9hb4w2-5p[hw24['y58h-q4[p9gbuq4-097gbw4p958gyh['dsfdgfsdfgafdbtyjaerotpjgertnu45n69078qhearfgq8907g4rlosadfgbhadjgmnyn q345o7utsrthnw49856yn2w[p40nhg5o2p045yn[2p408ny6h24p-0w65yjh2409yn4wqp57gh248w765tgq34-pt9hb4w2-5p[hw24['y58h-q4[p9gbuq4-097gbw4p958gyh['dsfdgfsdfgafdbtyjaerotpjgertnu45n69078qhearfgq8907g4rlosadfgbhadjgmnyn q345o7utsrthnw49856yn2w[p40nhg5o2p045yn[2p408ny6h24p-0w65yjh2409yn4wqp57gh248w765tgq34-pt9hb4w2-5p[hw24['y58h-q4[p9gbuq4-097gbw4p958gyh['dsfdgfsdfgafdbtyjaerotpjgertnu45n69078qhearfgq8907g4rlosadfgbhadjgmnyn q345o7utsrthnw49856yn2w[p40nhg5o2p045yn[2p408ny6h24p-0w65yjh2409yn4wqp57gh248w765tgq34-pt9hb4w2-5p[hw24['y58h-q4[p9gbuq4-097gbw4p958gyh['dsfdgfsdfgafdbtyjaerotpjgertnu45n69078qhearfgq8907g4rlosadfgbhadjgmnyn q345o7utsrthnw49856yn2w[p40nhg5o2p045yn[2p408ny6h24p-0w65yjh2409yn4wqp57gh248w765tgq34-pt9hb4w2-5p[hw24['y58h-q4[p9gbuq4-097gbw4p958gyh['v

### CODE REVIEW

**Comment by Istar-Eldritch** [comment]
wtf is that description?

**Comment by jamwaffles** [comment]
You gotta decode it 👌

**Comment by jamwaffles** [comment]
Also, question: should this go in repositive/event-store-rs instead? It shares no code in common, but other toolz like the event store explorer are kept there.

**Comment by jamwaffles** [comment]
Let's move it to the event store rs repo. The explorer is already in there. It makes sense to keep it all together instead of a repo full of different crap in different languages IMO, but I see the reasoning behind a tools repo.

-------- Original Message --------

**Comment by jamwaffles** [comment]
Closing in lieu of transfer to repositive/event-store-rs

**Pull request closed without merging**
