### PR TITLE
[B] Fix insert if not existing

### PR DESCRIPTION
**Pull request by Istar-Eldritch**

### CODE REVIEW

**Comment by petereast** [comment]
Is there no CI in this repo?

**Comment by danielsanchezd** [comment]
I think that CircleCI integration is not added until a later stage, when we need to start doing deployments.

**Comment by petereast** [comment]
Can't we just run a build & test pipeline?

**Comment by danielsanchezd** [comment]
Sure, go ahead and add it ;)

**Comment by petereast** [comment]
Ok, I'll make a PR

**Comment by Istar-Eldritch** [comment]
Yeah, we should add that CI. But during this week this repo is not the focus of the sprint. We'll focus on getting this on good shape next week.

**Pull request merged**
